version: '3.8'

services:
  # Laravel PHP Application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
    networks:
      - laravel

  # Nginx Service to serve the Laravel app
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # Vite Development Server for React
  vite:
    image: node:18-alpine
    container_name: laravel-vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    ports:
      - "5173:5173"  
    command: >
      sh -c "npm install && npm run dev" 
    depends_on:
      - app 
networks:
  laravel:
    driver: bridge
